EXCEPTION OCCURED IN 481 : site_1549_Hardev_Nagar_Bathinda_PPCB_15Min_2022.csv
Traceback (most recent call last):
  File "c:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\CPCB_Issues\AirPy_v2\main.py", line 101, in <module>
    local_df = correct_unit_inconsistency(local_df,filename, mixed_unit_identification, plot=True)
  File "c:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\CPCB_Issues\AirPy_v2\unit_inconsistency.py", line 394, in correct_unit_inconsistency
    plt.plot([1, np.nanmax(TEMP['NOx'])],[1,np.nanmax(TEMP['NOx'])], c = 'black')
  File "C:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\.venv\lib\site-packages\numpy\lib\nanfunctions.py", line 483, in nanmax
    res = np.amax(a, axis=axis, out=out, **kwargs)
  File "C:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\.venv\lib\site-packages\numpy\core\fromnumeric.py", line 2827, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\.venv\lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

================================================================



EXCEPTION OCCURED IN 1113 : site_5071_Phase-1_GIDC_Vapi_GPCB_15Min_2023.csv
Traceback (most recent call last):
  File "c:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\CPCB_Issues\AirPy_v2\main.py", line 103, in <module>
    local_df = correct_unit_inconsistency(local_df,filename, mixed_unit_identification, plot=True)
  File "c:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\CPCB_Issues\AirPy_v2\unit_inconsistency.py", line 394, in correct_unit_inconsistency
    plt.plot([1, np.nanmax(TEMP['NOx'])],[1,np.nanmax(TEMP['NOx'])], c = 'black')
  File "C:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\.venv\lib\site-packages\numpy\lib\nanfunctions.py", line 483, in nanmax
    res = np.amax(a, axis=axis, out=out, **kwargs)
  File "C:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\.venv\lib\site-packages\numpy\core\fromnumeric.py", line 2827, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\.venv\lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

================================================================



EXCEPTION OCCURED IN 1519 : site_5331_Kariavattom_Thiruvananthapuram_Kerala_PCB_15Min_2023.csv
Traceback (most recent call last):
  File "c:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\CPCB_Issues\AirPy_v2\main.py", line 103, in <module>
    local_df = correct_unit_inconsistency(local_df,filename, mixed_unit_identification, plot=True)
  File "c:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\CPCB_Issues\AirPy_v2\unit_inconsistency.py", line 394, in correct_unit_inconsistency
    plt.plot([1, np.nanmax(TEMP['NOx'])],[1,np.nanmax(TEMP['NOx'])], c = 'black')
  File "C:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\.venv\lib\site-packages\numpy\lib\nanfunctions.py", line 483, in nanmax
    res = np.amax(a, axis=axis, out=out, **kwargs)
  File "C:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\.venv\lib\site-packages\numpy\core\fromnumeric.py", line 2827, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\hitan\OneDrive\Desktop\MiniProjects\ML_NMIMS Codes\.venv\lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

================================================================



